### ISSUE TITLE
Unable to set default settings

### ISSUE THREAD

**Issue by rocker19943** [groboclown/p4ic4idea#143]
Hi, I'm unable to set default perforce settings for all projects

File -> Default settings -> Version Control -> Perforce 

IDE shows loading screen which does not complete.

EDIT:
Unable to save defined settings like P4PORT and P4USER too

![capture_idea](https://cloud.githubusercontent.com/assets/12564383/23460718/1f0d900c-fea0-11e6-8c41-21d68c8a1fe8.PNG)

**Comment by groboclown** [comment]
Thanks for the bug report.

I can't reproduce this locally.  Can you provide the following information?

* From your project directory, there should be the file `.idea/workspace.xml`.  Please provide the `<component name="P4ProjectConfigComponent">` section (and replace sensitive information with "foo").  The configuration UI is reading this information and trying to process it.
* See if the log file contains a stack trace with `net.groboclown` in it (you can see the log file through **Help** -> **Show Log in Explorer** for the Windows version of IntelliJ).  There might have been a problem that prevented the UI from responding.
* In the same directory as the log file, there might be a `threadDumps-freeze-(date)` directory.  If there is, can you inspect that to see if there's a `RUNNING` thread that includes a `net.groboclown` in the stack, and if so, and you provide that stack?

**Comment by groboclown** [comment]
Based on your comment about "P4PORT" and related settings not saving, have you upgraded to the latest  0.8.3 release?  That version included a fix for this issue, as well as a fix if you use the relative file configuration (if you have a big project, it used to scan your project  directory when you opened the config panel).

If you have upgraded, then there might be lingering problems that weren't addressed in that patch.

**Comment by rocker19943** [comment]
Seems I could figure out how to make P4PORT and P4USER save defined values, but still the plugin is unable to save value of P4 Client. The field resets after next load of the view, also the root directory does not match with client's root directory.

Here is the `P4ProjectConfigComponent` tag info you requested
```
<component name="P4ProjectConfigComponent">
    <mutable-composite-part>
      <require-password-data-part />
      <simple-data-part>
        <prop key="port" value="foo" />
        <prop key="authticket" value="$PROJECT_DIR$" />
        <prop key="trustticket" value="$PROJECT_DIR$" />
        <prop key="username" value="bar" />
      </simple-data-part>
      <client-name-data-part client-name="foo_bar" />
    </mutable-composite-part>
</component>
```
and the log file 
```
at net.groboclown.idea.p4ic.compat.idea163.AuthenticationCompat163$CredentialAuthStore.get(AuthenticationCompat163.java:78)
at net.groboclown.idea.p4ic.v2.server.authentication.PasswordManager.getPassword(PasswordManager.java:132)
at net.groboclown.idea.p4ic.v2.server.connection.AuthenticatedServer.reconnect(AuthenticatedServer.java:409)
at net.groboclown.idea.p4ic.v2.server.connection.AuthenticatedServer.checkoutServer(AuthenticatedServer.java:137)
at net.groboclown.idea.p4ic.v2.server.connection.ClientExec$2.run(ClientExec.java:178)
at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunWithSkippedPasswordCheck(ServerRunner.java:228)
at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunFor(ServerRunner.java:149)
at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunFor(ServerRunner.java:141)
at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.p4RunFor(ClientExec.java:263)
at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.runWithServer(ClientExec.java:173)
at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2.getServerInfo(P4Exec2.java:803)
at net.groboclown.idea.p4ic.v2.server.connection.ServerConnectionManager$CaseInsensitiveCheck.call(ServerConnectionManager.java:426)
at net.groboclown.idea.p4ic.v2.server.connection.ServerConnectionManager$CaseInsensitiveCheck.call(ServerConnectionManager.java:415)
at net.groboclown.idea.p4ic.v2.server.cache.state.AllClientsState.getStateForClient(AllClientsState.java:87)
at net.groboclown.idea.p4ic.v2.server.cache.CentralCacheManager.getClientCacheManager(CentralCacheManager.java:149)
at net.groboclown.idea.p4ic.v2.server.connection.ServerConnectionManager$ServerConfigStatus.getConnectionFor(ServerConnectionManager.java:355)
at net.groboclown.idea.p4ic.v2.server.connection.ServerConnectionManager.getConnectionFor(ServerConnectionManager.java:156)
at net.groboclown.idea.p4ic.v2.server.P4Server.<init>(P4Server.java:146)
at net.groboclown.idea.p4ic.v2.server.P4ServerManager.initializeServers(P4ServerManager.java:400)
at net.groboclown.idea.p4ic.v2.server.P4ServerManager.getServers(P4ServerManager.java:144)
at net.groboclown.idea.p4ic.extension.P4Vcs.getP4Servers(P4Vcs.java:690)
at net.groboclown.idea.p4ic.extension.P4Vcs.refreshServerConnectivity(P4Vcs.java:715)
at net.groboclown.idea.p4ic.extension.P4Vcs.access$500(P4Vcs.java:88)
at net.groboclown.idea.p4ic.extension.P4Vcs$5.run(P4Vcs.java:348)
at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.pullNextAction(ServerConnection.java:454)
at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.access$1300(ServerConnection.java:55)
at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$QueueRunner.run(ServerConnection.java:490)
java.lang.IllegalStateException: @NotNull method net/groboclown/idea/p4ic/ui/config/P4ProjectConfigurable.loadConfig must not return null
at net.groboclown.idea.p4ic.ui.config.P4ProjectConfigurable.loadConfig(P4ProjectConfigurable.java:101)
at net.groboclown.idea.p4ic.ui.config.P4ProjectConfigurable.createComponent(P4ProjectConfigurable.java:57)
2017-03-02 13:08:58,855 [  44026]  ERROR - pplication.impl.LaterInvocator - @NotNull method net/groboclown/idea/p4ic/ui/config/P4ProjectConfigurable.loadConfig must not return null 
java.lang.IllegalStateException: @NotNull method net/groboclown/idea/p4ic/ui/config/P4ProjectConfigurable.loadConfig must not return null
at net.groboclown.idea.p4ic.ui.config.P4ProjectConfigurable.loadConfig(P4ProjectConfigurable.java:101)
at net.groboclown.idea.p4ic.ui.config.P4ProjectConfigurable.isModified(P4ProjectConfigurable.java:63)
2017-03-02 13:09:43,476 [  88647]  ERROR - til.concurrency.QueueProcessor - @NotNull method net/groboclown/idea/p4ic/ui/config/P4ProjectConfigurable.loadConfig must not return null 
java.lang.IllegalStateException: @NotNull method net/groboclown/idea/p4ic/ui/config/P4ProjectConfigurable.loadConfig must not return null
at net.groboclown.idea.p4ic.ui.config.P4ProjectConfigurable.loadConfig(P4ProjectConfigurable.java:101)
at net.groboclown.idea.p4ic.ui.config.P4ProjectConfigurable.isModified(P4ProjectConfigurable.java:63)
at net.groboclown.idea.p4ic.v2.server.connection.AuthenticatedServer.disconnect(AuthenticatedServer.java:112)
at net.groboclown.idea.p4ic.v2.server.connection.AuthenticatedServer.finalize(AuthenticatedServer.java:397)
at net.groboclown.idea.p4ic.v2.server.connection.AuthenticatedServer.disconnect(AuthenticatedServer.java:112)
at net.groboclown.idea.p4ic.v2.server.connection.AuthenticatedServer.finalize(AuthenticatedServer.java:397)
at net.groboclown.idea.p4ic.v2.server.connection.AuthenticatedServer.disconnect(AuthenticatedServer.java:112)
at net.groboclown.idea.p4ic.v2.server.connection.AuthenticatedServer.finalize(AuthenticatedServer.java:397)
at net.groboclown.idea.p4ic.v2.server.connection.AuthenticatedServer.disconnect(AuthenticatedServer.java:112)
at net.groboclown.idea.p4ic.v2.server.connection.AuthenticatedServer.finalize(AuthenticatedServer.java:397)
```

**Comment by meyerjaw** [comment]
I too am having this issue. Let me know if you need additional log files to help you track this down.

**Comment by groboclown** [comment]
The IDE here is using the plugin in a weird state.  From the error message you posted, it looks like the plugin isn't fully loaded.  The P4ProjectConfigurable is the UI component that is in charge of showing the configuration pane and loading it with data.  The UI here is trying to reference the P4ProjectConfigComponent, which the IDE should load its state from the workspace.xml when the plugin is loaded.  However, that component isn't available yet (it returns null, hence the error).

As for the saving, it looks like the client name is being saved (`<client-name-data-part client-name="foo_bar" />`), but it may not be used correctly.

It looks like you're using PyCharm.  Which version are you using?  I can try it out and see if the plugin loading behavior is different there.

**Comment by rocker19943** [comment]
Yes you're right, I'm using latest (2016.3.2) community version of PyCharm for linux.

**Comment by groboclown** [comment]
I've pushed out a beta release of the plugin that you can try out.

https://github.com/groboclown/p4ic4idea/releases/tag/v0.8.4-beta.1

You'll need to download it, and in the IDE:

1. Open project settings (*Ctrl Alt S* on Windows, or just **File** -> **Settings...**).
2. Navigate to **Plugins** on the left side tree.
3. Click **Install plugin from disk...** and select the plugin zip that you downloaded.
4. Save the changes and restart the IDE.

**Comment by meyerjaw** [comment]
I'm still seeing the same error with the new build. My error is:
Server config {P4TRUST=(no value), P4PASSWD=<no plaintext password>, P4PORT=perforce:1666, P4TICKETS=(no value), P4USER=jmeyer, Server Fingerprint=(no value)} does not match {P4TRUST=(no value), P4CHARSET=(no value), P4PASSWD=<no plaintext password>, P4PORT=perforce:1666, P4TICKETS=(no value), P4USER=jmeyer, P4IGNORE=(no value), P4CLIENT=Development, Server Fingerprint=(no value), P4LOGINSSO=(no value), P4HOST=(no value)}

This appears to be different from the original issue and if needed, I can create a new ticket so to not hijack this issue. The end result is the same, I can't see anything in the settings section.

**Comment by groboclown** [comment]
Thanks for giving it a go.  That issue you're seeing is what was reported in #144.

BUT!  The error you posted was EXTREMELY useful.  It points out the flaw in the server comparison.  I should be able to fix this one quickly.

**Comment by groboclown** [comment]
Turned out that that specific problem was simple, but it uncovered a few others that were harder to tackle.

I have a new release out that should fix up many of these problems.

https://github.com/groboclown/p4ic4idea/releases/tag/v0.8.4-beta.2

There's still an issue with the password prompting, though.  If you are prompted for the password, you need to manually refresh the server listing, either by viewing the configuration UI again, or by using the status bar widget.

**Comment by rocker19943** [comment]
Thanks for updates,
I've used beta2 and was able to connect to perforce and even checkout/compare files
Plugin prompted a dialog to put my password in, but i guess it should not ask for it if I'm already logged in.
But still settings are not available from Default settings -> Version Control -> Perforce view, it now shows text "Select configuration element in the tree to edit its settings" instead of infinite loading screen.
And finally question remains... In the plugin settings, i see that the Root dir is equal to my project's path "/remote/projects/perforce_client_workspace/<some_path>/myProject" where the real perforce client configurations, the root directory is set to "/remote/projects/perforce_client_workspace/". Is it correct behavior or not ?

**Comment by groboclown** [comment]
The "root directory" displayed is as designed.  It won't list directories below the project root.  This is primarily for the rare individual who has a project that spans multiple workspaces.

I'll keep working to get those final problems ironed out.  Thanks for your patience.

**Comment by groboclown** [comment]
Another beta release.  It's creeping closer to being ready.

https://github.com/groboclown/p4ic4idea/releases/tag/v0.8.4-beta.3

**Comment by groboclown** [comment]
0.8.4 is out, which should fix this issue.  Please reopen the issue if you're still seeing it.
