### ISSUE TITLE
"Perforce Connection Error" with new version

### ISSUE THREAD

**Issue by ddperera** [groboclown/p4ic4idea#193]
Recently switched to the newest version of the plugin.  It was working very briefly, and correctly checked out a file, but now it's giving the following error:

Perforce Connection Error: Connection to Perforce server perforce:1666 failed: java.net.SocketTimeoutException: Read timed out

I don't have any other details, other than it's been seen on multiple machines here, so it might be an internal network/configuration related issue.

**Comment by groboclown** [comment]
Is the server name "perforce" and running on port 1666?  The error you're describing means that the currently configured P4PORT setting doesn't refer to a server it can contact.  The configuration of the updated plugin has changed from the old one, and the old configuration settings are not carried over into the new plugin.

What happens when you click the "Check Connection" button from the VCS directory mapping configuration?  (see https://github.com/groboclown/p4ic4idea#setting-up-the-plugin)

If it seems all the connection information is correct, then you can turn on some debugging.  I recommend turning on "p4" (no quotes) in the **Help** -> **Debug Log Settings...** dialog.  That will detail in the log file all the equivalent Perforce command-line executions.

**Comment by scriptacus** [comment]
This is from the logging
```
2018-12-12 12:09:53,690 [  18473]   INFO - onnection.ConnectCommandRunner - Finished listOpenedFilesChanges; started at Wed Dec 12 12:09:53 PST 2018, ended at Wed Dec 12 12:09:53 PST 2018 
2018-12-12 12:09:53,690 [  18473]   INFO - gin.extension.P4ChangeProvider - Processing changes in file://C:/Depot/XXXXX
2018-12-12 12:10:14,679 [  39462]   INFO - api.progress.AbstractTaskQueue - Timed out after 30000 milliseconds 
java.util.concurrent.CancellationException: Timed out after 30000 milliseconds
   at net.groboclown.p4.server.api.async.BlockingAnswer.blockingGet(BlockingAnswer.java:81)
   at net.groboclown.p4.server.api.async.BlockingAnswer.blockingGet(BlockingAnswer.java:38)
   at net.groboclown.p4.server.api.async.Answer.blockingGet(Answer.java:75)
   at net.groboclown.p4.server.impl.commands.QueryAnswerImpl.blockingGet(QueryAnswerImpl.java:95)
   at net.groboclown.p4plugin.extension.P4CommittedChangesProvider.getLocationFor(P4CommittedChangesProvider.java:155)
   at com.intellij.openapi.vcs.changes.committed.RepositoryLocationCache.lambda$getLocationUnderProgress$1(RepositoryLocationCache.java:66)
   at com.intellij.openapi.vcs.changes.committed.RepositoryLocationCache.getLocationUnderProgress(RepositoryLocationCache.java:72)
   at com.intellij.openapi.vcs.changes.committed.RepositoryLocationCache.getLocation(RepositoryLocationCache.java:55)
   at com.intellij.openapi.vcs.changes.committed.RootsCalculator.getLocation(RootsCalculator.java:103)
   at com.intellij.openapi.vcs.changes.committed.RootsCalculator.lambda$getRoots$0(RootsCalculator.java:64)
   at java.util.ArrayList.removeIf(ArrayList.java:1407)
   at com.intellij.openapi.vcs.changes.committed.RootsCalculator.getRoots(RootsCalculator.java:64)
   at com.intellij.openapi.vcs.changes.committed.CachesHolder.getAllRootsUnderVcs(CachesHolder.java:58)
   at com.intellij.openapi.vcs.changes.committed.CachesHolder.iterateAllCaches(CachesHolder.java:64)
   at com.intellij.openapi.vcs.changes.committed.CachesHolder.getAllCaches(CachesHolder.java:82)
   at com.intellij.openapi.vcs.changes.committed.CommittedChangesCache.loadIncomingChanges(CommittedChangesCache.java:595)
   at com.intellij.openapi.vcs.changes.committed.CommittedChangesCache.lambda$loadIncomingChangesAsync$9(CommittedChangesCache.java:707)
   at com.intellij.vcs.ProgressManagerQueue$MyWorker.run(ProgressManagerQueue.java:116)
   at com.intellij.vcs.ProgressManagerQueue$1.run(ProgressManagerQueue.java:50)
   at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:713)
   at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
   at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
   at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
   at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
   at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
   at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
   at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   at java.lang.Thread.run(Thread.java:745)
2018-12-12 12:10:14,850 [  39633]   WARN - nnection.P4RequestErrorHandler - Running an action with the Perforce server server:{P4TRUST=(unset), P4PASSWD=(set), P4PORT=perforce:1666, P4TICKETS=(unset), P4USER=XXXXXX, P4FINGERPRINT=(unset), P4LOGINSSO=(unset)} generated an error. 
com.perforce.p4java.exception.ConnectionException: java.net.SocketTimeoutException: Read timed out
   at com.perforce.p4java.common.base.P4JavaExceptions.throwConnectionException(P4JavaExceptions.java:63)
   at com.perforce.p4java.impl.mapbased.rpc.stream.RpcStreamConnection.getRpcPacket(RpcStreamConnection.java:529)
   at com.perforce.p4java.impl.mapbased.rpc.packet.RpcPacketDispatcher.dispatch(RpcPacketDispatcher.java:127)
   at com.perforce.p4java.impl.mapbased.rpc.NtsServerImpl.execMapCmdList(NtsServerImpl.java:377)
   at com.perforce.p4java.impl.mapbased.rpc.NtsServerImpl.execMapCmdList(NtsServerImpl.java:236)
   at com.perforce.p4java.impl.mapbased.server.cmd.BaseDelegator.execMapCmdList(BaseDelegator.java:139)
   at com.perforce.p4java.impl.mapbased.server.cmd.FstatDelegator.getExtendedFiles(FstatDelegator.java:62)
   at com.perforce.p4java.impl.mapbased.server.Server.getExtendedFiles(Server.java:1912)
   at net.groboclown.p4.server.impl.connection.impl.P4CommandUtil.getFilesDetails(P4CommandUtil.java:400)
   at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.lambda$listFilesDetails$40(ConnectCommandRunner.java:442)
   at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$null$2(SimpleConnectionManager.java:144)
   at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handleConnection(P4RequestErrorHandler.java:139)
   at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handle(P4RequestErrorHandler.java:70)
   at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$handleAsync$6(SimpleConnectionManager.java:568)
   at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$startPromise$8(SimpleConnectionManager.java:582)
   at net.groboclown.p4.server.api.async.AsyncAnswer.lambda$background$0(AsyncAnswer.java:49)
   at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: Read timed out
   at java.net.SocketInputStream.socketRead0(Native Method)
   at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
   at java.net.SocketInputStream.read(SocketInputStream.java:171)
   at java.net.SocketInputStream.read(SocketInputStream.java:141)
   at java.net.SocketInputStream.read(SocketInputStream.java:127)
   at com.perforce.p4java.impl.mapbased.rpc.stream.RpcSocketInputStream.read(RpcSocketInputStream.java:86)
   at com.perforce.p4java.impl.mapbased.rpc.stream.RpcStreamConnection.getRpcPacket(RpcStreamConnection.java:483)
   ... 20 more
2018-12-12 12:10:14,853 [  39636]   WARN - .components.UserErrorComponent - java.net.SocketTimeoutException: Read timed out 
com.perforce.p4java.exception.ConnectionException: java.net.SocketTimeoutException: Read timed out
   at com.perforce.p4java.common.base.P4JavaExceptions.throwConnectionException(P4JavaExceptions.java:63)
   at com.perforce.p4java.impl.mapbased.rpc.stream.RpcStreamConnection.getRpcPacket(RpcStreamConnection.java:529)
   at com.perforce.p4java.impl.mapbased.rpc.packet.RpcPacketDispatcher.dispatch(RpcPacketDispatcher.java:127)
   at com.perforce.p4java.impl.mapbased.rpc.NtsServerImpl.execMapCmdList(NtsServerImpl.java:377)
   at com.perforce.p4java.impl.mapbased.rpc.NtsServerImpl.execMapCmdList(NtsServerImpl.java:236)
   at com.perforce.p4java.impl.mapbased.server.cmd.BaseDelegator.execMapCmdList(BaseDelegator.java:139)
   at com.perforce.p4java.impl.mapbased.server.cmd.FstatDelegator.getExtendedFiles(FstatDelegator.java:62)
   at com.perforce.p4java.impl.mapbased.server.Server.getExtendedFiles(Server.java:1912)
   at net.groboclown.p4.server.impl.connection.impl.P4CommandUtil.getFilesDetails(P4CommandUtil.java:400)
   at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.lambda$listFilesDetails$40(ConnectCommandRunner.java:442)
   at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$null$2(SimpleConnectionManager.java:144)
   at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handleConnection(P4RequestErrorHandler.java:139)
   at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handle(P4RequestErrorHandler.java:70)
   at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$handleAsync$6(SimpleConnectionManager.java:568)
   at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$startPromise$8(SimpleConnectionManager.java:582)
   at net.groboclown.p4.server.api.async.AsyncAnswer.lambda$background$0(AsyncAnswer.java:49)
   at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: Read timed out
   at java.net.SocketInputStream.socketRead0(Native Method)
   at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
   at java.net.SocketInputStream.read(SocketInputStream.java:171)
   at java.net.SocketInputStream.read(SocketInputStream.java:141)
   at java.net.SocketInputStream.read(SocketInputStream.java:127)
   at com.perforce.p4java.impl.mapbased.rpc.stream.RpcSocketInputStream.read(RpcSocketInputStream.java:86)
   at com.perforce.p4java.impl.mapbased.rpc.stream.RpcStreamConnection.getRpcPacket(RpcStreamConnection.java:483)
   ... 20 more
2018-12-12 12:10:14,854 [  39637]   INFO - n.impl.SimpleConnectionManager - Command execution failed 
net.groboclown.p4.server.api.P4CommandRunner$ServerResultException: java.net.SocketTimeoutException: Read timed out
   at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.createServerResultException(P4RequestErrorHandler.java:121)
   at net.groboclown.p4.server.impl.connection.impl.MessageP4RequestErrorHandler.handleException(MessageP4RequestErrorHandler.java:333)
   at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handleConnection(P4RequestErrorHandler.java:141)
   at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handle(P4RequestErrorHandler.java:70)
   at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$handleAsync$6(SimpleConnectionManager.java:568)
   at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$startPromise$8(SimpleConnectionManager.java:582)
   at net.groboclown.p4.server.api.async.AsyncAnswer.lambda$background$0(AsyncAnswer.java:49)
   at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   at java.lang.Thread.run(Thread.java:745)
Caused by: com.perforce.p4java.exception.ConnectionException: java.net.SocketTimeoutException: Read timed out
   at com.perforce.p4java.common.base.P4JavaExceptions.throwConnectionException(P4JavaExceptions.java:63)
   at com.perforce.p4java.impl.mapbased.rpc.stream.RpcStreamConnection.getRpcPacket(RpcStreamConnection.java:529)
   at com.perforce.p4java.impl.mapbased.rpc.packet.RpcPacketDispatcher.dispatch(RpcPacketDispatcher.java:127)
   at com.perforce.p4java.impl.mapbased.rpc.NtsServerImpl.execMapCmdList(NtsServerImpl.java:377)
   at com.perforce.p4java.impl.mapbased.rpc.NtsServerImpl.execMapCmdList(NtsServerImpl.java:236)
   at com.perforce.p4java.impl.mapbased.server.cmd.BaseDelegator.execMapCmdList(BaseDelegator.java:139)
   at com.perforce.p4java.impl.mapbased.server.cmd.FstatDelegator.getExtendedFiles(FstatDelegator.java:62)
   at com.perforce.p4java.impl.mapbased.server.Server.getExtendedFiles(Server.java:1912)
   at net.groboclown.p4.server.impl.connection.impl.P4CommandUtil.getFilesDetails(P4CommandUtil.java:400)
   at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.lambda$listFilesDetails$40(ConnectCommandRunner.java:442)
   at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$null$2(SimpleConnectionManager.java:144)
   at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handleConnection(P4RequestErrorHandler.java:139)
   ... 10 more
Caused by: java.net.SocketTimeoutException: Read timed out
   at java.net.SocketInputStream.socketRead0(Native Method)
   at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
   at java.net.SocketInputStream.read(SocketInputStream.java:171)
   at java.net.SocketInputStream.read(SocketInputStream.java:141)
   at java.net.SocketInputStream.read(SocketInputStream.java:127)
   at com.perforce.p4java.impl.mapbased.rpc.stream.RpcSocketInputStream.read(RpcSocketInputStream.java:86)
   at com.perforce.p4java.impl.mapbased.rpc.stream.RpcStreamConnection.getRpcPacket(RpcStreamConnection.java:483)
   ... 20 more
```

**Comment by scriptacus** [comment]
Still happening, even with increased timeouts:
2018-12-17 12:51:48,766 [1367178]   INFO - .p4plugin.actions.P4EditAction - went offline while editing file://C:/depot/FILE.txt 
com.intellij.openapi.vcs.VcsConnectionProblem: went offline while editing file://C:/depot/FILE.txt
	at net.groboclown.p4plugin.actions.P4EditAction.lambda$null$3(P4EditAction.java:122)
	at net.groboclown.p4.server.impl.commands.OfflineActionAnswerImpl.whenOffline(OfflineActionAnswerImpl.java:31)
	at net.groboclown.p4plugin.actions.P4EditAction.lambda$null$4(P4EditAction.java:122)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:474)
	at net.groboclown.p4plugin.actions.P4EditAction.perform(P4EditAction.java:126)
	at net.groboclown.p4plugin.actions.BasicAction.actionPerformed(BasicAction.java:82)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:255)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:272)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:304)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:307)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:294)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:114)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:114)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:529)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:49)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:549)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:718)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


	2018-12-17 12:53:26,587 [  15030]  DEBUG -                         p4.api - p4java info: RPC connection to Perforce server perforce:1666 established 
2018-12-17 12:53:26,588 [  15031]  DEBUG -                         p4.api - p4java info: connected to Perforce server at perforce:1666 
2018-12-17 12:53:26,591 [  15034]   INFO -                             p4 - cmd (1): p4 info 
2018-12-17 12:53:26,626 [  15069]  DEBUG -                             p4 - Command 1 ran in 36 milliseconds 
2018-12-17 12:53:26,634 [  15077]   INFO -                             p4 - cmd (2): p4 client -o CLIENT-SUFFIX 
2018-12-17 12:53:26,640 [  15083]  DEBUG -                             p4 - Command 2 ran in 6 milliseconds 
2018-12-17 12:53:26,663 [  15106]   INFO - onnection.ConnectCommandRunner - Starting listOpenedFilesChanges at Mon Dec 17 12:53:26 PST 2018 
2018-12-17 12:53:26,666 [  15109]   INFO -                             p4 - cmd (3): p4 changes -i -cCLIENT-SUFFIX -m500 -spending -uCLIENT 
2018-12-17 12:53:26,675 [  15118]  DEBUG -                             p4 - Command 3 ran in 9 milliseconds 
2018-12-17 12:53:26,678 [  15121]   INFO -                             p4 - cmd (4): p4 change -s -o 378096 
2018-12-17 12:53:26,691 [  15134]  DEBUG -                             p4 - Command 4 ran in 13 milliseconds 
2018-12-17 12:53:26,695 [  15138]   INFO -                             p4 - cmd (5): p4 describe -s 378096 
2018-12-17 12:53:26,700 [  15143]  DEBUG -                             p4 - Command 5 ran in 5 milliseconds 
2018-12-17 12:53:26,701 [  15144]   INFO -                             p4 - cmd (6): p4 change -s -o 377617 
2018-12-17 12:53:26,712 [  15155]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 6585 ms 
2018-12-17 12:53:26,712 [  15155]  DEBUG -                             p4 - Command 6 ran in 11 milliseconds 
2018-12-17 12:53:26,713 [  15156]   INFO -                             p4 - cmd (7): p4 describe -s 377617 
2018-12-17 12:53:26,715 [  15158]   INFO - cloudConfig.CloudConfigManager - === End.updateInitStatus === 
2018-12-17 12:53:26,718 [  15161]  DEBUG -                             p4 - Command 7 ran in 5 milliseconds 
2018-12-17 12:53:26,718 [  15161]   INFO -                             p4 - cmd (8): p4 change -s -o 375994 
2018-12-17 12:53:26,731 [  15174]  DEBUG -                             p4 - Command 8 ran in 13 milliseconds 
2018-12-17 12:53:26,732 [  15175]   INFO -                             p4 - cmd (9): p4 describe -s 375994 
2018-12-17 12:53:26,736 [  15179]  DEBUG -                             p4 - Command 9 ran in 4 milliseconds 
2018-12-17 12:53:26,736 [  15179]   INFO -                             p4 - cmd (10): p4 change -s -o 372580 
2018-12-17 12:53:26,747 [  15190]  DEBUG -                             p4 - Command 10 ran in 11 milliseconds 
2018-12-17 12:53:26,748 [  15191]   INFO -                             p4 - cmd (11): p4 describe -s 372580 
2018-12-17 12:53:26,752 [  15195]  DEBUG -                             p4 - Command 11 ran in 4 milliseconds 
2018-12-17 12:53:26,753 [  15196]   INFO -                             p4 - cmd (12): p4 change -s -o 372179 
2018-12-17 12:53:26,766 [  15209]  DEBUG -                             p4 - Command 12 ran in 13 milliseconds 
2018-12-17 12:53:26,766 [  15209]   INFO -                             p4 - cmd (13): p4 describe -s 372179 
2018-12-17 12:53:26,772 [  15215]  DEBUG -                             p4 - Command 13 ran in 6 milliseconds 
2018-12-17 12:53:26,772 [  15215]   INFO -                             p4 - cmd (14): p4 change -s -o 372118 
2018-12-17 12:53:26,784 [  15227]  DEBUG -                             p4 - Command 14 ran in 12 milliseconds 
2018-12-17 12:53:26,784 [  15227]   INFO -                             p4 - cmd (15): p4 describe -s 372118 
2018-12-17 12:53:26,790 [  15233]  DEBUG -                             p4 - Command 15 ran in 6 milliseconds 
2018-12-17 12:53:26,790 [  15233]   INFO -                             p4 - cmd (16): p4 change -s -o 368402 
2018-12-17 12:53:26,801 [  15244]  DEBUG -                             p4 - Command 16 ran in 11 milliseconds 
2018-12-17 12:53:26,801 [  15244]   INFO -                             p4 - cmd (17): p4 describe -s 368402 
2018-12-17 12:53:26,805 [  15248]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 1401ms; general responsiveness: ok; EDT responsiveness: 2/2 sluggish 
2018-12-17 12:53:26,805 [  15248]  DEBUG -                             p4 - Command 17 ran in 4 milliseconds 
2018-12-17 12:53:26,805 [  15248]   INFO -                             p4 - cmd (18): p4 change -s -o 367940 
2018-12-17 12:53:26,816 [  15259]  DEBUG -                             p4 - Command 18 ran in 11 milliseconds 
2018-12-17 12:53:26,817 [  15260]   INFO -                             p4 - cmd (19): p4 describe -s 367940 
2018-12-17 12:53:26,821 [  15264]  DEBUG -                             p4 - Command 19 ran in 4 milliseconds 
2018-12-17 12:53:26,821 [  15264]   INFO -                             p4 - cmd (20): p4 change -s -o 367892 
2018-12-17 12:53:26,847 [  15290]  DEBUG -                             p4 - Command 20 ran in 26 milliseconds 
2018-12-17 12:53:26,848 [  15291]   INFO -                             p4 - cmd (21): p4 describe -s 367892 
2018-12-17 12:53:26,853 [  15296]  DEBUG -                             p4 - Command 21 ran in 5 milliseconds 
2018-12-17 12:53:26,853 [  15296]   INFO -                             p4 - cmd (22): p4 change -s -o 366088 
2018-12-17 12:53:26,868 [  15311]  DEBUG -                             p4 - Command 22 ran in 15 milliseconds 
2018-12-17 12:53:26,869 [  15312]   INFO -                             p4 - cmd (23): p4 describe -s 366088 
2018-12-17 12:53:26,875 [  15318]  DEBUG -                             p4 - Command 23 ran in 6 milliseconds 
2018-12-17 12:53:26,875 [  15318]   INFO -                             p4 - cmd (24): p4 change -s -o 365701 
2018-12-17 12:53:26,890 [  15333]  DEBUG -                             p4 - Command 24 ran in 15 milliseconds 
2018-12-17 12:53:26,890 [  15333]   INFO -                             p4 - cmd (25): p4 describe -s 365701 
2018-12-17 12:53:26,895 [  15338]  DEBUG -                             p4 - Command 25 ran in 5 milliseconds 
2018-12-17 12:53:26,895 [  15338]   INFO -                             p4 - cmd (26): p4 change -s -o 365347 
2018-12-17 12:53:26,907 [  15350]  DEBUG -                             p4 - Command 26 ran in 12 milliseconds 
2018-12-17 12:53:26,907 [  15350]   INFO -                             p4 - cmd (27): p4 describe -s 365347 
2018-12-17 12:53:26,911 [  15354]  DEBUG -                             p4 - Command 27 ran in 4 milliseconds 
2018-12-17 12:53:26,911 [  15354]   INFO -                             p4 - cmd (28): p4 change -s -o 362623 
2018-12-17 12:53:26,923 [  15366]  DEBUG -                             p4 - Command 28 ran in 12 milliseconds 
2018-12-17 12:53:26,923 [  15366]   INFO -                             p4 - cmd (29): p4 describe -s 362623 
2018-12-17 12:53:26,928 [  15371]  DEBUG -                             p4 - Command 29 ran in 5 milliseconds 
2018-12-17 12:53:26,928 [  15371]   INFO -                             p4 - cmd (30): p4 change -s -o 360009 
2018-12-17 12:53:26,930 [  15373]   INFO - j.ide.ui.OptionsTopHitProvider - 110 ms spent to cache options in project 
2018-12-17 12:53:26,930 [  15373]   INFO - tartup.impl.StartupManagerImpl - Some post-startup activities freeze UI for noticeable time. Please consider making them DumbAware to do them in background under modal progress, or just making them faster to speed up project opening. 
2018-12-17 12:53:26,930 [  15373]   INFO - tartup.impl.StartupManagerImpl - Activity run in 110ms on UI thread 
2018-12-17 12:53:26,939 [  15382]  DEBUG -                             p4 - Command 30 ran in 11 milliseconds 
2018-12-17 12:53:26,940 [  15383]   INFO -                             p4 - cmd (31): p4 describe -s 360009 
2018-12-17 12:53:26,945 [  15388]  DEBUG -                             p4 - Command 31 ran in 5 milliseconds 
2018-12-17 12:53:26,945 [  15388]   INFO -                             p4 - cmd (32): p4 change -s -o 357525 
2018-12-17 12:53:26,960 [  15403]  DEBUG -                             p4 - Command 32 ran in 15 milliseconds 
2018-12-17 12:53:26,960 [  15403]   INFO -                             p4 - cmd (33): p4 describe -s 357525 
2018-12-17 12:53:26,966 [  15409]  DEBUG -                             p4 - Command 33 ran in 6 milliseconds 
2018-12-17 12:53:26,966 [  15409]   INFO -                             p4 - cmd (34): p4 change -s -o 357307 
2018-12-17 12:53:26,981 [  15424]  DEBUG -                             p4 - Command 34 ran in 15 milliseconds 
2018-12-17 12:53:26,981 [  15424]   INFO -                             p4 - cmd (35): p4 describe -s 357307 
2018-12-17 12:53:26,986 [  15429]  DEBUG -                             p4 - Command 35 ran in 5 milliseconds 
2018-12-17 12:53:26,986 [  15429]   INFO -                             p4 - cmd (36): p4 change -s -o 356869 
2018-12-17 12:53:26,993 [  15436]   INFO - cloudConfig.CloudConfigManager - === StatusBar.start another widget: com.intellij.cloudConfig.StatusBarInfoManager$InfoComponent@4a837f24 === 
2018-12-17 12:53:26,997 [  15440]  DEBUG -                             p4 - Command 36 ran in 11 milliseconds 
2018-12-17 12:53:26,998 [  15441]   INFO -                             p4 - cmd (37): p4 describe -s 356869 
2018-12-17 12:53:27,002 [  15445]  DEBUG -                             p4 - Command 37 ran in 4 milliseconds 
2018-12-17 12:53:27,002 [  15445]   INFO -                             p4 - cmd (38): p4 change -s -o 355421 
2018-12-17 12:53:27,015 [  15458]  DEBUG -                             p4 - Command 38 ran in 13 milliseconds 
2018-12-17 12:53:27,015 [  15458]   INFO -                             p4 - cmd (39): p4 describe -s 355421 
2018-12-17 12:53:27,021 [  15464]  DEBUG -                             p4 - Command 39 ran in 6 milliseconds 
2018-12-17 12:53:27,021 [  15464]   INFO -                             p4 - cmd (40): p4 change -s -o 355007 
2018-12-17 12:53:27,032 [  15475]  DEBUG -                             p4 - Command 40 ran in 11 milliseconds 
2018-12-17 12:53:27,033 [  15476]   INFO -                             p4 - cmd (41): p4 describe -s 355007 
2018-12-17 12:53:27,037 [  15480]  DEBUG -                             p4 - Command 41 ran in 4 milliseconds 
2018-12-17 12:53:27,037 [  15480]   INFO -                             p4 - cmd (42): p4 change -s -o 335414 
2018-12-17 12:53:27,050 [  15493]  DEBUG -                             p4 - Command 42 ran in 13 milliseconds 
2018-12-17 12:53:27,050 [  15493]   INFO -                             p4 - cmd (43): p4 describe -s 335414 
2018-12-17 12:53:27,056 [  15499]  DEBUG -                             p4 - Command 43 ran in 6 milliseconds 
2018-12-17 12:53:27,056 [  15499]   INFO -                             p4 - cmd (44): p4 change -s -o 331654 
2018-12-17 12:53:27,068 [  15511]  DEBUG -                             p4 - Command 44 ran in 12 milliseconds 
2018-12-17 12:53:27,068 [  15511]   INFO -                             p4 - cmd (45): p4 describe -s 331654 
2018-12-17 12:53:27,077 [  15520]  DEBUG -                             p4 - Command 45 ran in 9 milliseconds 
2018-12-17 12:53:27,078 [  15521]   INFO -                             p4 - cmd (46): p4 fstat -Olhp 
2018-12-17 12:53:27,079 [  15522]  DEBUG -                             p4 - Command 46 ran in 1 milliseconds 
2018-12-17 12:53:27,085 [  15528]   INFO -                             p4 - cmd (47): p4 fstat -m5000 -edefault -Rc -Ro -Ol -Op -Oh //CLIENT-SUFFIX/... 
2018-12-17 12:53:27,091 [  15534]   INFO - j.ide.plugins.RepositoryHelper - using cached plugin list (updated at 12/17/2018 11:32 AM) 
2018-12-17 12:53:27,103 [  15546]  DEBUG -                             p4 - Command 47 ran in 18 milliseconds 
2018-12-17 12:53:27,106 [  15549]   INFO - onnection.ConnectCommandRunner - Finished listOpenedFilesChanges; started at Mon Dec 17 12:53:26 PST 2018, ended at Mon Dec 17 12:53:27 PST 2018 
2018-12-17 12:53:27,106 [  15549]  DEBUG -                         p4.api - p4java info: Disconnected RPC connection to Perforce server perforce:1666 
2018-12-17 12:53:27,107 [  15550]  DEBUG -                         p4.api - p4java info: disconnected from Perforce server at perforce:1666 
2018-12-17 12:53:27,107 [  15550]  DEBUG -                       p4.stats - p4java stats: RPC connection connected for 519 msec elapsed time 
2018-12-17 12:53:27,107 [  15550]  DEBUG -                       p4.stats - p4java stats: RPC server connections made: 1 
2018-12-17 12:53:27,107 [  15550]  DEBUG -                       p4.stats - p4java stats: RPC send ByteBuffer size: 0 
2018-12-17 12:53:27,107 [  15550]  DEBUG -                       p4.stats - p4java stats: RPC receive ByteBuffer size: 0 
2018-12-17 12:53:27,107 [  15550]  DEBUG -                       p4.stats - p4java stats: RPC packets sent: 50; RPC packets received: 115 
2018-12-17 12:53:27,107 [  15550]  DEBUG -                       p4.stats - p4java stats: stream sends: 50; stream recvs: 231 
2018-12-17 12:53:27,107 [  15550]  DEBUG -                       p4.stats - p4java stats: bytes sent: 11760; bytes received: 20970 bytes 
2018-12-17 12:53:27,107 [  15550]  DEBUG -                       p4.stats - p4java stats: largest RPC packet sent (bytes): 310; largest RPC packet receieved (bytes): 4910 
2018-12-17 12:53:27,107 [  15550]  DEBUG -                       p4.stats - p4java stats: largest socket send (bytes): 310; largest socket recv (bytes): 2915 
2018-12-17 12:53:27,107 [  15550]  DEBUG -                       p4.stats - p4java stats: RPC put buffer resizes: 0 
2018-12-17 12:53:27,107 [  15550]  DEBUG -                       p4.stats - p4java stats: RPC read buffer incomplete reads: 1 
2018-12-17 12:53:27,113 [  15556]   INFO - gin.extension.P4ChangeProvider - Processing changes in file://C:/depot/SUBDIR
2018-12-17 12:53:27,113 [  15556]  DEBUG -                         p4.api - p4java info: P4Java server factory called for Perforce server URI: p4jrpcnts://perforce:1666 
2018-12-17 12:53:27,113 [  15556]  DEBUG -                         p4.api - p4java info: Using Server implementation class: com.perforce.p4java.impl.mapbased.rpc.NtsServerImpl 
2018-12-17 12:53:27,113 [  15556]  DEBUG -                         p4.api - p4java info: Using program name: 'intellij-perforce-community-plugin-connection'; program version: '0.10.1' 
2018-12-17 12:53:27,113 [  15556]  DEBUG -                         p4.api - p4java info: Using tmp file directory: C:\Users\CLIENT\AppData\Local\Temp\tmp8507686812746708353 
2018-12-17 12:53:27,116 [  15559]  DEBUG -                         p4.api - p4java info: RPC connection to Perforce server perforce:1666 established 
2018-12-17 12:53:27,116 [  15559]  DEBUG -                         p4.api - p4java info: connected to Perforce server at perforce:1666 
2018-12-17 12:53:27,116 [  15559]   INFO -                             p4 - cmd (1): p4 info 
2018-12-17 12:53:27,137 [  15580]  DEBUG -                             p4 - Command 1 ran in 21 milliseconds 
2018-12-17 12:53:27,138 [  15581]   INFO -                             p4 - cmd (2): p4 client -o CLIENT-SUFFIX 
2018-12-17 12:53:27,146 [  15589]  DEBUG -                             p4 - Command 2 ran in 8 milliseconds 
2018-12-17 12:53:27,148 [  15591]   INFO -                             p4 - cmd (3): p4 fstat C:/depot/SUBDIR/...#have 
2018-12-17 12:53:27,352 [  15795]   INFO - j.ide.ui.OptionsTopHitProvider - 247 ms spent on EDT to cache options in project 
2018-12-17 12:53:28,430 [  16873]   INFO - CompilerWorkspaceConfiguration - Available processors: 16 
2018-12-17 12:53:56,606 [  45049]   INFO - api.progress.AbstractTaskQueue - Timed out after 30000 milliseconds 
java.util.concurrent.CancellationException: Timed out after 30000 milliseconds
	at net.groboclown.p4.server.api.async.BlockingAnswer.blockingGet(BlockingAnswer.java:81)
	at net.groboclown.p4.server.api.async.BlockingAnswer.blockingGet(BlockingAnswer.java:38)
	at net.groboclown.p4.server.api.async.Answer.blockingGet(Answer.java:75)
	at net.groboclown.p4.server.impl.commands.QueryAnswerImpl.blockingGet(QueryAnswerImpl.java:95)
	at net.groboclown.p4plugin.extension.P4CommittedChangesProvider.getLocationFor(P4CommittedChangesProvider.java:155)
	at com.intellij.openapi.vcs.changes.committed.RepositoryLocationCache.lambda$getLocationUnderProgress$1(RepositoryLocationCache.java:66)
	at com.intellij.openapi.vcs.changes.committed.RepositoryLocationCache.getLocationUnderProgress(RepositoryLocationCache.java:72)
	at com.intellij.openapi.vcs.changes.committed.RepositoryLocationCache.getLocation(RepositoryLocationCache.java:55)
	at com.intellij.openapi.vcs.changes.committed.RootsCalculator.getLocation(RootsCalculator.java:103)
	at com.intellij.openapi.vcs.changes.committed.RootsCalculator.lambda$getRoots$0(RootsCalculator.java:64)
	at java.util.ArrayList.removeIf(ArrayList.java:1407)
	at com.intellij.openapi.vcs.changes.committed.RootsCalculator.getRoots(RootsCalculator.java:64)
	at com.intellij.openapi.vcs.changes.committed.CachesHolder.getAllRootsUnderVcs(CachesHolder.java:58)
	at com.intellij.openapi.vcs.changes.committed.CachesHolder.iterateAllCaches(CachesHolder.java:64)
	at com.intellij.openapi.vcs.changes.committed.CachesHolder.getAllCaches(CachesHolder.java:82)
	at com.intellij.openapi.vcs.changes.committed.CommittedChangesCache.loadIncomingChanges(CommittedChangesCache.java:580)
	at com.intellij.openapi.vcs.changes.committed.CommittedChangesCache.lambda$loadIncomingChangesAsync$9(CommittedChangesCache.java:692)
	at com.intellij.vcs.ProgressManagerQueue$MyWorker.run(ProgressManagerQueue.java:116)
	at com.intellij.vcs.ProgressManagerQueue$1.run(ProgressManagerQueue.java:50)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-12-17 12:54:30,390 [  78833]   INFO - gin.extension.P4ChangeProvider - Processing changes in file://C:/depot/SUBDIR 
2018-12-17 12:54:40,174 [  88617]   INFO - clown.p4plugin.extension.P4Vcs - Checking if file exists in VCS; if so, then it will use the `VcsHandleType` to edit the file.  File: [C:/depot/FILE.txt]; status: ADDED

**Comment by groboclown** [comment]
Thanks for the logging information.  That last problem was due to the task queue being full (maxed out on simultaneous connections) and they took too long to run.  That *might* be an issue with a command not terminating correctly.  That can easily be tracked by adding debug logging for:

```
#net.groboclown.p4.server.impl.util.TraceableSemaphore
```

This will trace what processes gain access to the queue, which processes are pending access, and how long each one is taking.

**Comment by groboclown** [comment]
I'm looking now into ensuring that the values for the socket timeout are used correctly, and that retries are made for socket timeouts.  This should also not be marked as going offline when it happens.

**Comment by groboclown** [comment]
Looks like there was another bug, where changing the sso timeout and lock timeout would only take effect when a project is opened.  I'm testing out a fix for that and the new retry logic now.

**Comment by groboclown** [comment]
New version is released with the added feature.  Please report back if this helps solve the issue, or if it still is a problem.

**Comment by scriptacus** [comment]
Using the new version I had better luck for a while, but I noticed is was "Refreshing VCS history" for quite some time, so I reduced all of the fetch max values (changelist, history, etc.. ) to their minimums.  After working for a few minutes, I get the following, and IntelliJ slows to a crawl

12/21/2018
11:38 AM	Error Moving Files to Perforce Changelist: Waiting for lock timed out: exceeded 30000 milliseconds

11:38 AM	Low Memory
					The IDE is running low on memory and this might affect performance. Please consider increasing available heap.
					Configure

**Comment by groboclown** [comment]
Thanks for the feedback!  Looks like a bug that was fixed in beta about a memory leak is back, maybe in another form.  Did you see this with the default or altered retry value?

**Comment by scriptacus** [comment]
I still get this issue with the currently available build.  Is there anything I can do dump the memory usage and put it here?

**Comment by groboclown** [comment]
New version is available (0.10.3) which includes the logging.

**Comment by groboclown** [comment]
Is this still an issue?
